dist: bionic
os:
 - linux
language: shell
services: docker
env:
- HHVM_VERSION=3.25.3
- HHVM_VERSION=3.26.3
- HHVM_VERSION=3.27-lts-latest
- HHVM_VERSION=3.28.3
- HHVM_VERSION=3.29-latest
- HHVM_VERSION=3.30-latest
- HHVM_VERSION=4.0-latest
- HHVM_VERSION=4.4-latest
- HHVM_VERSION=4.8-latest
- HHVM_VERSION=4.16-latest
- HHVM_VERSION=4.25-latest
- HHVM_VERSION=4.26-latest
- HHVM_VERSION=4.32-latest
- HHVM_VERSION=4.40-latest
- HHVM_VERSION=4.48-latest
- HHVM_VERSION=4.56-latest
- HHVM_VERSION=4.64-latest
# version 4.70 was skipped, testing on hhvm 4.69 instead
- HHVM_VERSION=4.69-latest
- HHVM_VERSION=latest
- HHVM_VERSION=nightly

install:
- docker pull hhvm/hhvm:$HHVM_VERSION
script:
- docker run --rm -w /var/source -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION ./.travis.sh
